name: Daily Java Tests with Allure

on:
  schedule:
    - cron: '0 5 * * *' # 8:00 по МСК
  workflow_dispatch: # ручной запуск
    inputs:
      testClass:
        description: 'Набор smoke тестов'
        default: 'SmokeSuite'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3️⃣ Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Run tests with Allure
      - name: Run only SmokeSuite
        run: mvn clean test -Dtest=${{ github.event.inputs.testClass}} io.qameta.allure:allure-maven:report

      # 5️⃣ Upload Allure report as artifact
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
          destination_dir: allure-report

      # 6️⃣ Notify Telegram with test status and link to artifact
      - name: Notify Telegram
        if: always()
        run: |
          STATUS="${{ job.status }}"
          ALLURE_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure-report/index.html"
          MESSAGE="*JUnit Tests Result*: *${STATUS}*\n📦 Repo: ${{ github.repository }}\n🔀 Branch: ${{ github.ref_name }}\n[📄 View Allure Report](${ALLURE_URL})"
          echo "Sending Telegram notification..."
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d parse_mode=Markdown \
            -d text="$MESSAGE"