name: Daily Java Tests with Allure

on:
  schedule:
    - cron: '0 5 * * *' # 8:00 по МСК
  workflow_dispatch: # ручной запуск
    inputs:
      testClass:
        description: 'Набор smoke тестов'
        default: 'SmokeSuite'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout (проверка)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK 11 (настройка)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3️⃣ Cache Maven dependencies (кэширование зависимостей)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Run tests with Allure (запуск теста с Allure)
      - name: Run only SmokeSuite
        run: mvn clean test -Dtest=${{ github.event.inputs.testClass}} io.qameta.allure:allure-maven:report

      # 5️⃣ Upload Allure report as artifact (загрузка отчета)
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

#      # 📦 Сборка и генерация Allure отчёта
#      - name: Run tests and generate Allure report
#        run: |
#          mvn clean test
#          mvn allure:report
#
#      # 📑 Устанавливаем wkhtmltopdf для конвертации HTML → PDF
#      - name: Install wkhtmltopdf
#        run: sudo apt-get install -y wkhtmltopdf
#
#      # 📃 Конвертируем Allure report в PDF
#      - name: Convert Allure report to PDF
#        run: |
#          mkdir -p pdf-report
#          wkhtmltopdf target/site/allure-maven-plugin/index.html pdf-report/allure-report.pdf
#
#      # 📤 Отправляем PDF в Telegram
#      - name: Send Allure PDF to Telegram
#        env:
#          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
#        run: |
#          curl -F document=@pdf-report/allure-report.pdf \
#          "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
#          -F chat_id="${TELEGRAM_CHAT_ID}" \
#          -F caption="📊 Allure Report PDF"


      # 6️⃣ Notify Telegram with test status and link to artifact (отправка отчета в ТГ)
      - name: Notify Telegram
        if: always() # ✅ всегда отправляем
        run: |
          STATUS="${{ job.status }}"
          ARTIFACT_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          MESSAGE="*JUnit Tests Result*: *${STATUS}*\n\
          📄 Suite: AllTestsSuite\n\
          [🔗 View Allure Report Artifact](${ARTIFACT_URL})"
          echo "Sending Telegram notification..."
          RESPONSE=$(curl -s -w "\nHTTP_CODE:%{http_code}" -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d parse_mode=Markdown \
            -d text="$MESSAGE")
          echo "$RESPONSE"
