name: Daily Java Tests with Allure

on:
  schedule:
    - cron: '0 5 * * *' # 8:00 по МСК
  workflow_dispatch: # ручной запуск

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3️⃣ Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Run tests with Allure
      - name: Run tests and generate Allure results
        run: mvn clean test io.qameta.allure:allure-maven:report

      # 5️⃣ Upload Allure report as artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      # 6️⃣ Notify Telegram with test status and link to artifact
      - name: Notify Telegram
        if: failure() || success()
        run: |
          STATUS="${{ job.status }}"
          ARTIFACT_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          MESSAGE="🚨 *JUnit Tests Result*: *${STATUS}*\nRepo: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\n[🔗 View Allure Report Artifact](${ARTIFACT_URL})"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d parse_mode=Markdown \
            -d text="$MESSAGE"